---
title: "4. Combined states GSEA comparisons"
output: html_document
---

Preliminary summary




```{r include=FALSE}
source("../../helper_scripts.R")

library(ggplot2)
library(readxl)
library(pheatmap)
library(msigdbr)
library(stringr)

global_crosstab <- read.table("../../proteomics/data/global_data/ptrc_ex18_crosstab_global_gene_corrected.txt")
phospho_crosstab <- read.table("../../proteomics/data/phospho_data/ptrc_ex18_crosstab_phospho_siteID_corrected.txt")
phospho_prot_crosstab <- read.table("../../proteomics/data/phospho_data/ptrc_ex18_crosstab_phospho_SiteID_prot_corrected.txt")
meta <- read_excel("../../proteomics/data/Exp18_metadata_01-14-2021.xlsx") %>%
  filter(!is.na(Index)) %>%
  mutate(Index = as.character(Index),
         Plex = as.character(Plex),
         comp1_ = paste(State, Treatment, sep = "_and_")) %>% as.data.frame()
rownames(meta) <- meta$Index

colnames(global_crosstab) <- sub("^X", "", colnames(global_crosstab))
colnames(phospho_crosstab) <- sub("^X", "", colnames(phospho_crosstab))
colnames(phospho_prot_crosstab) <- sub("^data.", "", colnames(phospho_prot_crosstab))


m_global <- MSnSet(exprs = global_crosstab %>% as.matrix(), 
                   pData = meta[colnames(global_crosstab), ])

m_phospho <- MSnSet(exprs = phospho_crosstab %>% as.matrix(), 
                    pData = meta[colnames(phospho_crosstab), ])

pData(m_global) <- pData(m_global) %>%
  mutate(Treatment_cs = case_when(Treatment != "G" ~ Treatment,
                                  TRUE ~ paste(Treatment, State, sep = "_")))
pData(m_phospho) <- pData(m_phospho) %>%
  mutate(Treatment_cs = case_when(Treatment != "G" ~ Treatment,
                                  TRUE ~ paste(Treatment, State, sep = "_")))

```



```{r Getting GSEA DB tables}
t2g_hallmark <- msigdbr(species = "Homo sapiens", category = "H") %>% 
  dplyr::select(gs_name, gene_symbol)

t2g_gobp <- msigdbr(species = "Homo sapiens", category = "C5", subcategory = "BP") %>% 
  dplyr::select(gs_name, gene_symbol) %>%
  mutate(gs_name = gsub("_", " ", gs_name))

t2g_reactome <- msigdbr(species = "Homo sapiens", category = "C2", subcategory = "REACTOME") %>% 
  dplyr::select(gs_name, gene_symbol) %>%
  mutate(gs_name = gsub("_", " ", gs_name))

t2g_kegg <- msigdbr(species = "Homo sapiens", category = "C2", subcategory = "KEGG") %>% 
  dplyr::select(gs_name, gene_symbol) %>%
  mutate(gs_name = gsub("_", " ", gs_name))

```


```{r Extra msigs, eval=FALSE, include=FALSE}

t2g_humanpheno <- msigdbr(species = "Homo sapiens", category = "C5", subcategory = "HPO") %>% 
  dplyr::select(gs_name, gene_symbol) %>%
  mutate(gs_name = gsub("_", " ", gs_name))

t2g_gocc <- msigdbr(species = "Homo sapiens", category = "C5", subcategory = "CC") %>% 
  dplyr::select(gs_name, gene_symbol) %>%
  mutate(gs_name = gsub("_", " ", gs_name))

t2g_gomf <- msigdbr(species = "Homo sapiens", category = "C5", subcategory = "MF") %>% 
  dplyr::select(gs_name, gene_symbol) %>%
  mutate(gs_name = gsub("_", " ", gs_name))

t2g_wikipath <- msigdbr(species = "Homo sapiens", category = "C2", subcategory = "WIKIPATHWAYS") %>% 
  dplyr::select(gs_name, gene_symbol) %>%
  mutate(gs_name = gsub("_", " ", gs_name))

t2g_pid <- msigdbr(species = "Homo sapiens", category = "C2", subcategory = "PID") %>% 
  dplyr::select(gs_name, gene_symbol) %>%
  mutate(gs_name = gsub("_", " ", gs_name))



t2g_biocarta <- msigdbr(species = "Homo sapiens", category = "C2", subcategory = "BIOCARTA") %>% 
  dplyr::select(gs_name, gene_symbol) %>%
  mutate(gs_name = gsub("_", " ", gs_name))

t2g_curatedpath <- msigdbr(species = "Homo sapiens", category = "C2", subcategory = "CP") %>% 
  dplyr::select(gs_name, gene_symbol) %>%
  mutate(gs_name = gsub("_", " ", gs_name))

t2g_oncogenic <- msigdbr(species = "Homo sapiens", category = "C6") %>%
  dplyr::select(gs_name, gene_symbol) %>%
  mutate(gs_name = gsub("_", " ", gs_name))

t2g_immunesigdb <- msigdbr(species = "Homo sapiens", category = "C7", subcategory = "IMMUNESIGDB") %>%
  dplyr::select(gs_name, gene_symbol) %>%
  mutate(gs_name = gsub("_", " ", gs_name))

t2g_immune <- msigdbr(species = "Homo sapiens", category = "C7", ) %>%
  dplyr::select(gs_name, gene_symbol) %>%
  mutate(gs_name = gsub("_", " ", gs_name))

```


```{r}
contrasts <- c()
for (Treatment in c("GD", "GV", "GVD", "G_Early", "G_Late")){
  contrasts_new = paste0("Treatment_cs", Treatment, "-Treatment_csnone")
  # contrasts_new = paste0(Treatment, "-none")
  contrasts <- c(contrasts, contrasts_new)

}

```


```{r}
GSEA_helper(m_global, contrasts, t2g_hallmark, "Hallmark", "Treatment_cs")
GSEA_helper(m_global, contrasts, t2g_reactome, "Reactome", "Treatment_cs")
GSEA_helper(m_global, contrasts, t2g_kegg, "KEGG", "Treatment_cs")
GSEA_helper(m_global, contrasts, t2g_gobp, "GOBP", "Treatment_cs")

```


```{r}
KSEA_helper(m_phospho, contrasts, "Treatment_cs")

```



```{r Combining enrichment tables}
all_combined_gsea <- data.frame()
for (file in list.files(pattern = "^GSEA_.+_combined.txt$")){
  print(file)
  DB = sub("(^.+_.+)_.+$", "\\1", file) %>%
    gsub("_", " ", .)
  xx <- read.table(file, sep = "\t") %>%
    mutate(DB = DB) %>%
    select(Pathway = Description, enrichment = NES, p.adjust, contrast, DB) %>%
    mutate(Treatment = sub("^Treatment_cs(.+)-Treatment_csnone", "\\1", contrast))
  all_combined_gsea <- rbind(all_combined_gsea, xx)
  print(ncol(xx))
}

write.table(all_combined_gsea, "GSEA_combined.txt", quote = F, sep = "\t")

all_combined_ksea <- data.frame()
for (file in list.files(pattern = "^KSEA_.+_combined.txt$")){
  print(file)
  DB = sub("(^.+_.+)_.+$", "\\1", file) %>%
    gsub("_", " ", .)
  xx <- read.table(file, sep = "\t") %>%
    mutate(DB = DB) %>%
    select(Pathway = pathway, enrichment, p.adjust = adj_p_val, contrast, DB) %>%
    mutate(Treatment = sub("^Treatment_cs(.+)-Treatment_csnone", "\\1", contrast))
  all_combined_ksea <- rbind(all_combined_ksea, xx)
  print(ncol(xx))
}

write.table(all_combined_ksea, "KSEA_combined.txt", quote = F, sep = "\t")
write.table(rbind(all_combined_gsea, all_combined_ksea), "enrichment_combined.txt", quote = F, sep = "\t")

```







