---
title: "Ex18 GSEA comparisons"
output: html_document
---

Preliminary summary




```{r include=FALSE}
source("../../helper_scripts.R")

library(ggplot2)
library(readxl)
library(pheatmap)
library(msigdbr)
library(stringr)

global_crosstab <- read.table("../../proteomics/data/global_data/ptrc_ex18_crosstab_global_gene_corrected.txt")
phospho_crosstab <- read.table("../../proteomics/data/phospho_data/ptrc_ex18_crosstab_phospho_siteID_corrected.txt")
phospho_prot_crosstab <- read.table("../../proteomics/data/phospho_data/ptrc_ex18_crosstab_phospho_SiteID_prot_corrected.txt")
meta <- read_excel("../../proteomics/data/Exp18_metadata_01-14-2021.xlsx") %>%
  filter(!is.na(Index)) %>%
  mutate(Index = as.character(Index),
         Plex = as.character(Plex),
         comp1_ = paste(State, Treatment, sep = "_and_")) %>% as.data.frame()
rownames(meta) <- meta$Index

colnames(global_crosstab) <- sub("^X", "", colnames(global_crosstab))
colnames(phospho_crosstab) <- sub("^X", "", colnames(phospho_crosstab))
colnames(phospho_prot_crosstab) <- sub("^data.", "", colnames(phospho_prot_crosstab))


m_global <- MSnSet(exprs = global_crosstab %>% as.matrix(), 
                   pData = meta[colnames(global_crosstab), ])

m_phospho <- MSnSet(exprs = phospho_crosstab %>% as.matrix(), 
                    pData = meta[colnames(phospho_crosstab), ])

```



```{r Getting GSEA DB tables}
t2g_hallmark <- msigdbr(species = "Homo sapiens", category = "H") %>% 
  dplyr::select(gs_name, gene_symbol)

t2g_gobp <- msigdbr(species = "Homo sapiens", category = "C5", subcategory = "BP") %>% 
  dplyr::select(gs_name, gene_symbol) %>%
  mutate(gs_name = gsub("_", " ", gs_name))

t2g_reactome <- msigdbr(species = "Homo sapiens", category = "C2", subcategory = "REACTOME") %>% 
  dplyr::select(gs_name, gene_symbol) %>%
  mutate(gs_name = gsub("_", " ", gs_name))

t2g_kegg <- msigdbr(species = "Homo sapiens", category = "C2", subcategory = "KEGG") %>% 
  dplyr::select(gs_name, gene_symbol) %>%
  mutate(gs_name = gsub("_", " ", gs_name))

```


```{r Extra msigs, eval=FALSE, include=FALSE}

t2g_humanpheno <- msigdbr(species = "Homo sapiens", category = "C5", subcategory = "HPO") %>% 
  dplyr::select(gs_name, gene_symbol) %>%
  mutate(gs_name = gsub("_", " ", gs_name))

t2g_gocc <- msigdbr(species = "Homo sapiens", category = "C5", subcategory = "CC") %>% 
  dplyr::select(gs_name, gene_symbol) %>%
  mutate(gs_name = gsub("_", " ", gs_name))

t2g_gomf <- msigdbr(species = "Homo sapiens", category = "C5", subcategory = "MF") %>% 
  dplyr::select(gs_name, gene_symbol) %>%
  mutate(gs_name = gsub("_", " ", gs_name))

t2g_wikipath <- msigdbr(species = "Homo sapiens", category = "C2", subcategory = "WIKIPATHWAYS") %>% 
  dplyr::select(gs_name, gene_symbol) %>%
  mutate(gs_name = gsub("_", " ", gs_name))

t2g_pid <- msigdbr(species = "Homo sapiens", category = "C2", subcategory = "PID") %>% 
  dplyr::select(gs_name, gene_symbol) %>%
  mutate(gs_name = gsub("_", " ", gs_name))



t2g_biocarta <- msigdbr(species = "Homo sapiens", category = "C2", subcategory = "BIOCARTA") %>% 
  dplyr::select(gs_name, gene_symbol) %>%
  mutate(gs_name = gsub("_", " ", gs_name))

t2g_curatedpath <- msigdbr(species = "Homo sapiens", category = "C2", subcategory = "CP") %>% 
  dplyr::select(gs_name, gene_symbol) %>%
  mutate(gs_name = gsub("_", " ", gs_name))

t2g_oncogenic <- msigdbr(species = "Homo sapiens", category = "C6") %>%
  dplyr::select(gs_name, gene_symbol) %>%
  mutate(gs_name = gsub("_", " ", gs_name))

t2g_immunesigdb <- msigdbr(species = "Homo sapiens", category = "C7", subcategory = "IMMUNESIGDB") %>%
  dplyr::select(gs_name, gene_symbol) %>%
  mutate(gs_name = gsub("_", " ", gs_name))

t2g_immune <- msigdbr(species = "Homo sapiens", category = "C7", ) %>%
  dplyr::select(gs_name, gene_symbol) %>%
  mutate(gs_name = gsub("_", " ", gs_name))

```


```{r}
contrasts <- c()
for (Treatment in c("GD", "GV", "GVD", "G")){
  contrasts_early = paste0("comp1_Early_and_", Treatment, "-comp1_Parental_and_none")
  contrasts_late = paste0("comp1_Late_and_", Treatment, "-comp1_Parental_and_none")
  contrasts <- c(contrasts, contrasts_early, contrasts_late)

}

```


```{r}
GSEA_helper(m_global, contrasts, t2g_hallmark, "Hallmark", "comp1_")
GSEA_helper(m_global, contrasts, t2g_reactome, "Reactome", "comp1_")
GSEA_helper(m_global, contrasts, t2g_kegg, "KEGG", "comp1_")
GSEA_helper(m_global, contrasts, t2g_gobp, "GOBP", "comp1_")

```


Combining the GV and GVD treatments to highlight the functions in V.


```{r}
m_global_2 <- m_global
pData(m_global_2) <- pData(m_global_2) %>%
  dplyr::mutate(Treatment_2 = case_when(Treatment %in% c("GV", "GVD") ~ "GV_or_GVD",
                                        TRUE ~ Treatment),
                comp1_ = paste(State, Treatment_2, sep = "_and_"))
GSEA_helper_single(m_global_2, "comp1_Early_and_GV_or_GVD-comp1_Parental_and_none", t2g_gobp, "GOBP", "comp1_")
GSEA_helper_single(m_global_2, "comp1_Late_and_GV_or_GVD-comp1_Parental_and_none", t2g_gobp, "GOBP", "comp1_")
GSEA_helper_single(m_global_2, "comp1_Early_and_GV_or_GVD-comp1_Early_and_G", t2g_gobp, "GOBP", "comp1_")
GSEA_helper_single(m_global_2, "comp1_Late_and_GV_or_GVD-comp1_Late_and_G", t2g_gobp, "GOBP", "comp1_")

GSEA_helper_single(m_global_2, "comp1_Early_and_GV_or_GVD-comp1_Parental_and_none", t2g_hallmark, "Hallmark", "comp1_")
GSEA_helper_single(m_global_2, "comp1_Late_and_GV_or_GVD-comp1_Parental_and_none", t2g_hallmark, "Hallmark", "comp1_")
GSEA_helper_single(m_global_2, "comp1_Early_and_GV_or_GVD-comp1_Early_and_G", t2g_hallmark, "Hallmark", "comp1_")
GSEA_helper_single(m_global_2, "comp1_Late_and_GV_or_GVD-comp1_Late_and_G", t2g_hallmark, "Hallmark", "comp1_")

GSEA_helper_single(m_global_2, "comp1_Early_and_GV_or_GVD-comp1_Parental_and_none", t2g_kegg, "KEGG", "comp1_")
GSEA_helper_single(m_global_2, "comp1_Late_and_GV_or_GVD-comp1_Parental_and_none", t2g_kegg, "KEGG", "comp1_")
GSEA_helper_single(m_global_2, "comp1_Early_and_GV_or_GVD-comp1_Early_and_G", t2g_kegg, "KEGG", "comp1_")
GSEA_helper_single(m_global_2, "comp1_Late_and_GV_or_GVD-comp1_Late_and_G", t2g_kegg, "KEGG", "comp1_")

GSEA_helper_single(m_global_2, "comp1_Early_and_GV_or_GVD-comp1_Parental_and_none", t2g_reactome, "Reactome", "comp1_")
GSEA_helper_single(m_global_2, "comp1_Late_and_GV_or_GVD-comp1_Parental_and_none", t2g_reactome, "Reactome", "comp1_")
GSEA_helper_single(m_global_2, "comp1_Early_and_GV_or_GVD-comp1_Early_and_G", t2g_reactome, "Reactome", "comp1_")
GSEA_helper_single(m_global_2, "comp1_Late_and_GV_or_GVD-comp1_Late_and_G", t2g_reactome, "Reactome", "comp1_")

```


Combining the GD and GVD treatments to highlight the functions in D.


```{r}
m_global_2 <- m_global
pData(m_global_2) <- pData(m_global_2) %>%
  dplyr::mutate(Treatment_2 = case_when(Treatment %in% c("GD", "GVD") ~ "GD_or_GVD",
                                        TRUE ~ Treatment),
                comp1_ = paste(State, Treatment_2, sep = "_and_"))
GSEA_helper_single(m_global_2, "comp1_Early_and_GD_or_GVD-comp1_Parental_and_none", t2g_gobp, "GOBP", "comp1_")
GSEA_helper_single(m_global_2, "comp1_Late_and_GD_or_GVD-comp1_Parental_and_none", t2g_gobp, "GOBP", "comp1_")
GSEA_helper_single(m_global_2, "comp1_Early_and_GD_or_GVD-comp1_Early_and_G", t2g_gobp, "GOBP", "comp1_")
GSEA_helper_single(m_global_2, "comp1_Late_and_GD_or_GVD-comp1_Late_and_G", t2g_gobp, "GOBP", "comp1_")

GSEA_helper_single(m_global_2, "comp1_Early_and_GD_or_GVD-comp1_Parental_and_none", t2g_hallmark, "Hallmark", "comp1_")
GSEA_helper_single(m_global_2, "comp1_Late_and_GD_or_GVD-comp1_Parental_and_none", t2g_hallmark, "Hallmark", "comp1_")
GSEA_helper_single(m_global_2, "comp1_Early_and_GD_or_GVD-comp1_Early_and_G", t2g_hallmark, "Hallmark", "comp1_")
GSEA_helper_single(m_global_2, "comp1_Late_and_GD_or_GVD-comp1_Late_and_G", t2g_hallmark, "Hallmark", "comp1_")

GSEA_helper_single(m_global_2, "comp1_Early_and_GD_or_GVD-comp1_Parental_and_none", t2g_kegg, "KEGG", "comp1_")
GSEA_helper_single(m_global_2, "comp1_Late_and_GD_or_GVD-comp1_Parental_and_none", t2g_kegg, "KEGG", "comp1_")
GSEA_helper_single(m_global_2, "comp1_Early_and_GD_or_GVD-comp1_Early_and_G", t2g_kegg, "KEGG", "comp1_")
GSEA_helper_single(m_global_2, "comp1_Late_and_GD_or_GVD-comp1_Late_and_G", t2g_kegg, "KEGG", "comp1_")

GSEA_helper_single(m_global_2, "comp1_Early_and_GD_or_GVD-comp1_Parental_and_none", t2g_reactome, "Reactome", "comp1_")
GSEA_helper_single(m_global_2, "comp1_Late_and_GD_or_GVD-comp1_Parental_and_none", t2g_reactome, "Reactome", "comp1_")
GSEA_helper_single(m_global_2, "comp1_Early_and_GD_or_GVD-comp1_Early_and_G", t2g_reactome, "Reactome", "comp1_")
GSEA_helper_single(m_global_2, "comp1_Late_and_GD_or_GVD-comp1_Late_and_G", t2g_reactome, "Reactome", "comp1_")

```


















