
---
title: "Ex18 combined tables upload"
output: html_document
---

Preliminary summary




```{r include=FALSE}
library(dplyr)
source("../../helper_scripts.R")
source("../../util/synapseUtil.R")
syn <- synapseLogin()


```


## Upload all GSEA tables


```{r}
DBs = c("Reactome", "GOBP", "KEGG", "Hallmark")

for (DB in DBs){
  results <- list.files(".", paste0("GSEA_.*_", DB, ".txt"))
  combined <- data.frame()
  for (res in results){
    xx <- read.table(res, sep = '\t') %>%
      mutate(contrast = gsub("Treatment_cs", "", contrast),
             contrast = sub("-none", " vs Parental", contrast))
    combined <- rbind(combined, xx)
  }
  
  openxlsx::write.xlsx(combined, paste0("GSEA_exp12_states_combined_vs_parental_", DB, ".xlsx"))
  synapseStore(paste0("GSEA_exp12_states_combined_vs_parental_", DB, ".xlsx"), "syn51118958")
}

```





## Upload KSEA tables


```{r}
xx <- read.table("KSEA_NetworKIN_5_combined.txt", sep = "\t") %>% 
  mutate(contrast = gsub("Treatment_cs", "", contrast),
         contrast = sub("-none", " vs Parental", contrast))
openxlsx::write.xlsx(xx, file = "KSEA_exp12_states_combined_vs_parental_PSP_NetworKIN5.xlsx")
synapseStore("KSEA_exp12_states_combined_vs_parental_PSP_NetworKIN5.xlsx", "syn51118958")

```






